### ISSUE TITLE
Seperate repo to host library versions over CDN

### ISSUE THREAD

**Issue by bvhme** [Amsterdam/amsterdam.github.io#15]
X3 over GH-Pages version for Armoede Dashboard @kerkuil and potential other future libs.

**Comment by MauriceHendriks** [comment]
Any idea what the repository would be? One simply called `library` or plural `libraries`?

**Comment by bvhme** [comment]
If we're being clear about it it might be worth naming it in lieu of what it's goal is: serving versions of libraries developed by others we are dependent on from our own trusted source as to keep our projects functioning. 

I like the idea of calling it `libraries`, however perhaps `dependency-cache` (or `library-cache`) better serves our purpose.

**Comment by MauriceHendriks** [comment]
> If we're being clear about it it might be worth naming it in lieu of what it's goal is: serving versions of libraries developed by others we are dependent on from our own trusted source as to keep our projects functioning.

And not only that, but also having our CDN libraries in version control, so others can easily find our code as we use in the in the field.

> I like the idea of calling it libraries, however perhaps dependency-cache (or library-cache) better serves our purpose.

A `README.md` with describes it as a CDN is not 'self-documenting' enough?

**Comment by bvhme** [comment]
@kerkuil I've created https://github.com/Amsterdam/libraries in line with your feedback above.

Does this solve this issue?
