### ISSUE TITLE
X3 folder in this repo

### ISSUE THREAD

**Issue by bvhme** [Amsterdam/amsterdam.github.io#3]
Is the [x3 version hosted in this repo](https://github.com/Amsterdam/amsterdam.github.io/tree/master/x3/v0.1) still used? If not I'd like to clean it up.

Do you know @kerkuil?

**Comment by bvhme** [comment]
The 'readme.txt' in that folder says 'code used in armoede dashboard 2016'.

**Comment by MauriceHendriks** [comment]
The readme says it all :+1:

**Comment by bvhme** [comment]
Thanks!
