### ISSUE TITLE
Snap de Brief

### ISSUE THREAD

**Issue by bvhme** [Amsterdam/amsterdam.github.io#38]
http://clarity.codefor.nl/cbase/tiltshift-fix-f183b292/usecase/snap-de-brief-c775b9be0100fba0870f2cb4a854a891

**Comment by bvhme** [comment]
The Snap de Brief website at https://www.snapdebrief.nl/ seems to be down

**Comment by KelPas** [comment]
@bvhme Thats correct, because the hosting contract is not renewed..

**Comment by bvhme** [comment]
That is too bad...

Thanks @KelvinPaska :)

I'm closing this issue since there are no longer any use cases for this codebase available.

I've added https://github.com/Amsterdam/brievenhulp/issues/1 to it's issues as well, which I'll try to do something with soon.
