### ISSUE TITLE
Schema is unreadable with current width

### ISSUE THREAD

**Issue by Lytrix** [Amsterdam/amsterdam.github.io#52]
The PNG schema is not easily readable when the current width is used: https://amsterdam.github.io/guides/data-pipeline/

2 Proposals: 

1. break out wide images
2. add it as a banner image full width at the top.

**Comment by bvhme** [comment]
Can I suggest a third option for now, linking the image to the file so that it can be viewed in the browser at full size.

**Comment by bvhme** [comment]
I think the current solution works best from a design perspective. We can have a look at this again if new patterns emerge :)
