### ISSUE TITLE
General non-style content from `contrib-guide`

### ISSUE THREAD

**Issue by bvhme** [Amsterdam/amsterdam.github.io#8]
There is contributing information on [contrib-guide](https://amsterdam.github.io/contrib-guide/). See to it that the relevant parts get adopted into this project and specifics distributed to the specific projects.

# What is on `contrib-guide`
Here I'm trying to make an index of the content that needs to be part of the new page

## `index`
- [ ] Goals: agreements on design #31 , 
- [X] Goals: code reviews #12 
- [x] Goals: collaboration #1 
- [x] How to use (this document as reference for how it should be)
- [x] Example of how to refer back to this guide
- [x] This should be a living doc

## `code`
See #27 

### Code Review

- See #12 

## `projects`

- See #19

## `self`

- [x] How to contribute to this guide

## `python`

- See #14

**Comment by bvhme** [comment]
Hey @pieterb and @spreeker,

These are the things I'm intended to copy from `contrib-guide` to which you have contributed most. As I'm moving these things into the `amsterdam.github.io` guides as much as possible I had a few questions:

Should we make style-guides (eg 'How we write python') for all of our development or should they be project specific and thus in repo's with projects? Idem for some of the things on the code-review list.

What do you think?

**Comment by bvhme** [comment]
After speeking to @spreeker briefly, we're going to start with a Python guide here.

See #14

**Comment by MauriceHendriks** [comment]
It could be usefull to use the artistic style documentation to answer all the code style questions.
http://astyle.sourceforge.net/astyle.html

**Comment by bvhme** [comment]
I'm closing this issue as to not seeing how I can easily resolve this, and/or knowing how to fix it.
